# This workflow creates brand specific packages for the supported web browsers.

name: Create packages for Chromium and Firefox extension stores

jobs:
  create-zip-files:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v5

    - name: Create chromium package
      env: BROWSER_NAME: chromium
      run: sh ./create-package.sh

    - name: Create firefox package
      env: BROWSER_NAME: firefox
      run: sh ./create-package.sh
