# This workflow creates brand specific packages for the supported web browsers.

name: Create browser packages

on: workflow_dispatch

jobs:
  create-zip-files:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v5

    - name: Create chromium package
      env: 
        BROWSER_NAME: chromium
      run: sh ./.github/workflows/create-zip-package.sh

    - name: Create firefox package
      env: 
        BROWSER_NAME: firefox
      run: sh ./.github/workflows/create-zip-package.sh

    - name: Upload packages
      uses: actions/upload-artifact@v4
      with:
        name: extension-packages
        path: ./dist/*.zip
        if-no-files-found: error
