# This workflow creates brand specific packages for the supported web browsers.
# See https://github.com/actions/create-release for background about the create and upload release steps

name: Release new browser packages

on: 
  workflow_dispatch:
    inputs:
      version: 
        required: true
        type: string

jobs:
  create-zip-files:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v5

    - name: Create chromium package
      env: 
        BROWSER_NAME: chromium
      run: sh ./.github/workflows/create-package.sh

    - name: Create firefox package
      env: 
        BROWSER_NAME: firefox
      run: sh ./.github/workflows/create-package.sh
